# generated by datamodel-codegen:
#   filename:  http://localhost:8000/openapi.json
#   timestamp: 2026-04-17T11:08:03+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, SecretStr, conint, constr
from enum import Enum
from typing import Any


class ArchiveCreate(BaseModel):
    name: str = Field(..., title="Name")


class ArchivePublic(BaseModel):
    name: str = Field(..., title="Name")
    id: int = Field(..., title="Id")


class ArchiveRole(Enum):
    owner = "owner"
    editor = "editor"
    viewer = "viewer"


class AuthorPublic(BaseModel):
    name: str = Field(..., title="Name")
    id: int = Field(..., title="Id")


class BodyLoginApiV1UsersLoginPost(BaseModel):
    grant_type: constr(pattern=r"^password$") | None = Field(None, title="Grant Type")
    username: str = Field(..., title="Username")
    password: SecretStr = Field(..., title="Password")
    scope: str | None = Field("", title="Scope")
    client_id: str | None = Field(None, title="Client Id")
    client_secret: SecretStr | None = Field(None, title="Client Secret")


class ExportStrategyType(Enum):
    all_in_one = "all_in_one"
    splitted = "splitted"
    by_element = "by_element"


class InstrumentConfig(BaseModel):
    copies: int = Field(..., title="Copies")
    other_options: list[str] = Field(..., title="Other Options")


class InstrumentsPreset(BaseModel):
    name: str = Field(..., title="Name")
    instruments: dict[str, InstrumentConfig] | None = Field(None, title="Instruments")


class PieceCreate(BaseModel):
    cod: int = Field(..., title="Cod")
    name: str = Field(..., title="Name")
    handwrited: bool = Field(..., title="Handwrited")
    parted: bool = Field(..., title="Parted")
    digitalized: bool = Field(..., title="Digitalized")
    archive_id: int = Field(..., title="Archive Id")
    author_id: int | None = Field(None, title="Author Id")
    author_name: str | None = Field(None, title="Author Name")
    type_id: int | None = Field(None, title="Type Id")
    type_name: str | None = Field(None, title="Type Name")


class PresetPrintJobConfig(BaseModel):
    export_strategy: ExportStrategyType | None = "by_element"
    group_by_instrument: bool | None = Field(False, title="Group By Instrument")
    sorted_export: bool | None = Field(False, title="Sorted Export")
    ignore_preset_copies: bool | None = Field(False, title="Ignore Preset Copies")
    add_piece_number: bool | None = Field(False, title="Add Piece Number")
    add_cover_page: bool | None = Field(False, title="Add Cover Page")
    cover_title: str | None = Field("Music Pdf Manager", title="Cover Title")
    add_index: bool | None = Field(False, title="Add Index")
    index_title: str | None = Field("Índice", title="Index Title")
    index_subtitle: str | None = Field("", title="Index Subtitle")
    add_blank_page_after_index: bool | None = Field(
        False, title="Add Blank Page After Index"
    )


class PrinteableFile(BaseModel):
    copies: conint(ge=1) | None = Field(1, title="Copies")
    archive_id: int = Field(..., title="Archive Id")
    piece_std_name: str = Field(..., title="Piece Std Name")
    file_name: str = Field(..., title="File Name")


class PrinteablePiece(BaseModel):
    copies: conint(ge=1) | None = Field(1, title="Copies")
    std_name: str = Field(..., title="Std Name")


class SimplePrintJob(BaseModel):
    files: list[PrinteableFile] = Field(..., title="Files")


class Token(BaseModel):
    access_token: str = Field(..., title="Access Token")
    token_type: str = Field(..., title="Token Type")


class TypePublic(BaseModel):
    name: str = Field(..., title="Name")
    id: int = Field(..., title="Id")


class UploadStagingResponse(BaseModel):
    file_id: str = Field(..., title="File Id")
    original_filename: str = Field(..., title="Original Filename")
    size_bytes: int = Field(..., title="Size Bytes")
    message: str = Field(..., title="Message")


class UserCreate(BaseModel):
    name: str = Field(..., title="Name")
    email: str = Field(..., title="Email")
    role_id: int | None = Field(None, title="Role Id")
    password: str = Field(..., title="Password")


class UserPublic(BaseModel):
    name: str = Field(..., title="Name")
    email: str = Field(..., title="Email")
    role_id: int | None = Field(None, title="Role Id")
    id: int = Field(..., title="Id")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class BodyAddPieceToArchiveApiV1ArchivesArchiveIdPiecesPost(BaseModel):
    piece: PieceCreate
    files: list[str] = Field(..., title="Files")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class PiecePublic(BaseModel):
    cod: int = Field(..., title="Cod")
    name: str = Field(..., title="Name")
    handwrited: bool = Field(..., title="Handwrited")
    parted: bool = Field(..., title="Parted")
    digitalized: bool = Field(..., title="Digitalized")
    id: int = Field(..., title="Id")
    author: AuthorPublic | None = None
    type: TypePublic | None = None
    archive: ArchivePublic | None = None
    std_name: str = Field(
        ..., description="Dynamically concatenated cod and name.", title="Std Name"
    )


class PiecesPreset(BaseModel):
    name: str = Field(..., description="The name of the pieces preset", title="Name")
    instruments_preset_name: str = Field(
        ...,
        description="The name of the instruments preset associated with this pieces preset",
        title="Instruments Preset Name",
    )
    pieces: list[PrinteablePiece] = Field(
        ...,
        description="A list of piece std names included in this preset",
        title="Pieces",
    )
    user_id: int = Field(
        ...,
        description="The ID of the user who owns this preset and the instruments preset",
        title="User Id",
    )


class PiecesPresetCreate(BaseModel):
    name: str = Field(..., description="The name of the pieces preset", title="Name")
    instruments_preset_name: str = Field(
        ...,
        description="The name of the instruments preset associated with this pieces preset",
        title="Instruments Preset Name",
    )
    pieces: list[PrinteablePiece] = Field(
        ...,
        description="A list of piece std names included in this preset",
        title="Pieces",
    )


class PresetPrintJobPublic(BaseModel):
    preset_name: str = Field(..., title="Preset Name")
    archive_id: int = Field(..., title="Archive Id")
    pieces: list[PrinteablePiece] = Field(..., title="Pieces")
    config: PresetPrintJobConfig
    solved_fails: dict[str, dict[str, str]] | None = Field({}, title="Solved Fails")
