RELATIVE_ARCHIVE_PATH = "../ArchivoDigital"
DB_NAME = "archivo.db"
OPTIONS_OF_INSTRUMENTS = ["GENERAL","OBOE 1","OBOE 2","FLAUTÍN","FLAUTA 1","FLAUTA 2","REQUINTO","CLARINETE PRAL","CLARINETE 1","CLARINETE 2","CLARINETE 3","CLARINETE BAJO","FAGOT 1","FAGOT 2","SAXOFÓN 1","SAXOFÓN 2","SAXOFÓN TENOR 1","SAXOFÓN TENOR 2","SAXOFÓN BARÍTONO","TROMPA 1","TROMPA 2","TROMPA 3","TROMPA 4","FLISCORNO 1","FLISCORNO 2","TROMPETA 1","TROMPETA 2","TROMPETA 3","TROMBÓN 1","TROMBÓN 2","TROMBÓN 3","BOMBARDINO 1","BOMBARDINO 2","TUBA 1","TUBA 2","PERCUSIÓN 1","PERCUSIÓN 2","PERCUSIÓN 3","BOMBO","CAJA","PLATOS"]
DIR_SCORES = "/partituras/"
DIR_EXTRAS = "/extras/"
DIR_COMPRESS = "/compress/"
