import os 

RELATIVE_ARCHIVE_PATH = os.path.join("..","ArchivoDigital")
RELATIVE_NEW_PATH = os.path.join("..","newArchivo")
DB_FILE_NAME = "archivo.db"
DB_NAME = "AMVR_archive"
OPTIONS_OF_INSTRUMENTS_NUMBERED = ["GENERAL","OBOE 1","OBOE 2","FLAUTÍN","FLAUTA 1","FLAUTA 2","REQUINTO","CLARINETE PRAL","CLARINETE 1","CLARINETE 2","CLARINETE 3","CLARINETE BAJO","FAGOT 1","FAGOT 2","SAXOFÓN 1","SAXOFÓN 2","SAXOFÓN TENOR 1","SAXOFÓN TENOR 2","SAXOFÓN BARÍTONO","TROMPA 1","TROMPA 2","TROMPA 3","TROMPA 4","FLISCORNO 1","FLISCORNO 2","TROMPETA 1","TROMPETA 2","TROMPETA 3","TROMBÓN 1","TROMBÓN 2","TROMBÓN 3","BOMBARDINO 1","BOMBARDINO 2","TUBA 1","TUBA 2","PERCUSIÓN 1","PERCUSIÓN 2","PERCUSIÓN 3","BOMBO","CAJA","PLATOS"]
OPTIONS_OF_INSTRUMENTS_ESP = ["GENERAL","OBOE","FLAUTIN","FLAUTA","REQUINTO","PRINCIPAL","CLARINETE","CLARINETE BAJO","FAGOT","SAXOFON","SAXOFON TENOR","SAXOFON BARITONO","TROMPA","FLISCORNO","TROMPETA","TROMBON","BOMBARDINO","TUBA","PERCUSION","BOMBO","CAJA","PLATOS"]
OPTIONS_OF_INSTRUMENTS_VAL = ["GENERAL","OBOE","FLAUTI","FLAUTA","REQUINT","PRINCIPAL","CLARINET","CLARINET BAIX","FAGOT","SAXOFON","SAXOFON TENOR","SAXOFON BARITON","TROMPA","FLISCORN","TROMPETA","TROMBO","BOMBARDI","TUBA","PERCUSIO","BOMBO","CAIXA","PLATS"]
DIR_SCORES = "partituras"
DIR_EXTRAS = "extras"
IGNORE_FILES  = [".DS_Store"]
HYPHEN = "-" 
MAX_COPIES = 20 #Max copies of the combo box next to the add button in select mode 
COVER_PARTITURES_GUIDE = os.path.join("data","portada_dossier_partituras.jpg")

#CAMBIE DIR_SCORE y DIR_EXTRAS de partituras a partituras. Alomejor luego pueden haber problemas por eso. Para tenerlo en cuenta