import os

#Delete .DS_Store ._* files that are generated by macOS
def delete_junk_files(path):
    for root, dirs, files in os.walk(path):
            for file in files:
                if file == '.DS_Store' or '._.DS_Store' in file:
                    os.remove(os.path.join(root, file))
                    print(f'Archive .DS_Store eliminado en: {root}')
                if file.startswith("._"):
                    os.remove(os.path.join(root, file))
                    print(f"Archive with ._: {file}")
